version: '3.9'
services: 
  bb-flaskapp: 
    image: bbalp:pycodev1 
    build: 
      context: .  # location of dockerfile 
      dockerfile:  alpine.dockerfile # name of dockerfile
    container_name: bbalpCont 
    ports:
    - 3015:5000  
# above steps have merging of build and run 