version: '3.9'
services: 
  bb-sprintboot: 
    image: bbspring:tomcatv1 
    build: 
      context: .  # location of dockerfile 
      dockerfile:  Dockerfile # name of dockerfile
    container_name: bbspringCont 
    ports:
    - 3150:8080  
# above steps have merging of build and run 