apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bb-tomcat-deploy
  name: bblb1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: bb-tomcat-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
